// <auto-generated />
namespace Transpo.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class identityfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(identityfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201606211956028_identity-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
