// <auto-generated />
namespace Transpo.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nonrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nonrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "201606281956096_nonrequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
